AWSTemplateFormatVersion: 2010-09-09
Description: Checkpoint3

Parameters:
  OmaNimi:
    Type: String
    Default: "Mitja"

  UusinAmi:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  Avain:
    Description: EC2-avainpari SSH-yhteyttä varten
    Type: 'AWS::EC2::KeyPair::KeyName'

Resources:

  SecurityGrouppi:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ec2 security group
      GroupName: mitja-cf-ec2-sg
      SecurityGroupIngress:
        - FromPort: 22
          ToPort: 22
          IpProtocol: Tcp
          CidrIp: 0.0.0.0/0
        - FromPort: 80
          ToPort: 80
          IpProtocol: Tcp
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: mitja-checkpoint3

  Instanssi:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref UusinAmi
      InstanceType: t2.nano
      KeyName: !Ref Avain
      SecurityGroupIds:
        - !Ref SecurityGrouppi
      Tags:
        - Key: Owner
          Value: Mitja
        - Key: Name
          Value: mitja-checkpoint3
      UserData:
          Fn::Base64:
            Fn::Join:
              - "\n"
              - - "#!/bin/bash"
                - "amazon-linux-extras install epel"
                - "amazon-linux-extras install nginx1"
                - "systemctl start nginx"

  UusiBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mitja-checkpoint3
        Tags:
          - Key: Owner
            Value: !Ref OmaNimi

  UusiParametri:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Value: !GetAtt UusiBucket.Arn

Outputs:
  InstanssiDNS:
    Value: !GetAtt Instanssi.PublicDnsName



